### ISSUE TITLE
Frequent stalls when converting songs

### ISSUE THREAD

**Issue by Sixdd6** [KrystianLesniak/Clone-Hero-Songs-Compressor#31]
I've been converting my collection over to the new format and certain setlists frequently cause the program to hang after a song is converted, the app has to be closed and reopened to start the next song when this happens.

So far the setlist that has given the most issues is Parallax Hero though I did have it stop a few times on other lists.
Let me know if there is a log somewhere I can give, I didn't see one in the app folder.

**Comment by KrystianLesniak** [comment]
Hello. Thank you for contribution! I will take a look into this issue soon.

**Comment by KrystianLesniak** [comment]
Thanks for providing problematic set list. It allowed me to detect and fix issue.

Fix has been applied in release: https://github.com/KrystianLesniak/Clone-Hero-Songs-Compressor/releases/tag/v0.1.1-beta
